### ISSUE TITLE
Animation retargeting workflow

### ISSUE THREAD

**Issue by wilg** [soupday/cc_unity_tools_HDRP#67]
I have tried using multiple animation packs from the Unity Asset Store, all of which result in the character's feet being in the wrong position. I see that there are animation retargeting tools, but that requires me manually going through each animation, saving a new one, and using it in my animator controller.

I think it should be possible to correct this by instead adjusting the Avatar import settings for the CC FBX file. That way it applies to any animation I use automatically. Is this correct? Perhaps this could be implemented instead of the existing workflow?

![image](https://user-images.githubusercontent.com/54353/216173488-518df3be-a634-4b4a-9492-86d729f976f4.png)

**Comment by wilg** [comment]
The section on Unity Avatars in this documentation from my animation pack may be helpful:

[READ ME!-Mocap Online-Unity Animation Notes 3-13-19.pdf](https://github.com/soupday/cc_unity_tools_HDRP/files/10562002/READ.ME.-Mocap.Online-Unity.Animation.Notes.3-13-19.pdf)

**Comment by soupday** [comment]
If you are **only** using animations from one source, all with **exactly** the same avatar, then yes you could adjust the CC character's avatar to match and save yourself some work.

But: If you then try to use animations from any other sources with different avatar's that need a different avatar correction, they will not work correctly because your character's avatar has already been altered for the earlier animations and changing that will break those animations.

The correct work flow is to re-target the animations to the character you want to play the animations on. You don't re-target the character to the animations.

But also, to close the mouth on (nearly all of) these animations from the asset store, you need to write out a new animation file anyway.

I also find that you need to enable foot IK in the animation states of the animation controller to correct the foot positioning. Especially for Mixamo animations, those are terrible for foot sliding.

You could try adjusting the avatar used by the source animations to make it more aligned with the CC avatar. That can work.

**Comment by wilg** [comment]
Ah, just as you commented I figured out what was causing the issue - it was my FinalIK foot grounding system. Disabling that fixes my issue with the legs. I will experiment some more since I don't think it's directly related to CC. Thanks for your reply!
